plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

branches:
  - name: dev/*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'
