plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"

branches:
  - name: "+([0-9])?(.{+([0-9]),x}).x"
  - name: main
